name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
        },
        {
run-name: actions/setup-java@v3.9.0

    # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
   
  # You may pin to the exact commit or the version.
  # uses: parasoft/execute-job-action@1899d360584e281e027c537d2df0f75a1115776e:
    # CTP URL

    # CTP Username

    # CTP Password

    # CTP Test Execution Job Name

    # Abort the job after timeout exceeded

    # Timeout value in minutes

    # Publish test execution results to DTP

    # DTP URL
 
    # DTP Username

    # DTP Password

    # DTP Project Name
 
    # Build ID to send to DTP

    # Session Tag to send to DTP

    # Append the test variable set environment name to the session tag
  
